### PR TITLE
Added file on france

### PR DESCRIPTION
**Pull request by sstevens2**

### CODE REVIEW

**Comment by pshriwise** [comment]
Thank you for this addition, @sstevens2! If you could please add the largest city to this file that would be really helpful.

**Comment by pshriwise** [comment]
Nevermind. It looks good the way it is. Thanks again! 🎉

**Comment by bam241** [comment]
last estimate France population to 67,297 million :)

**Comment by bam241** [comment]
@pshriwise you merged too quickly... the data were not accurate :)

**Comment by sstevens2** [comment]
Sorry @bam241 using old data.  You can add a PR on the lessons [here](https://github.com/UW-Madison-ACI/20170830-git-novice) if you want it to be more up to date.

**Comment by bam241** [comment]
It is not a big deal, it was only to tease @pshriwise  ;)

**Pull request merged**
